- cuda_core/cuda/core/experimental/_program.py
- cuda_core/cuda/core/experimental/_utils.py
Close #142.
- We always pass the NVRTC handle to `handle_return()` except when creating/destroying the handle
- We form the error message in 2 steps, and the first step does not need any NVRTC handle
> Fix NVRTC error handling

- cuda_core/pyproject.toml
Close #190.
Blocked by #188. (After it's merged, we'll support both CUDA 11 & 12, and the simple constraint added in this PR will be safe.)
This change should be revisited once we start working on #105. Right now, it's a way to ensure the bindings are available in the user environment.
> Make `cuda-core` (tentatively) depend on `cuda-python`

- cuda_core/cuda/core/experimental/_launcher.py
- cuda_core/cuda/core/experimental/_module.py
Close #187.
This PR fixes two issues:
1. `launch` does not support the old `cuLaunchKernel` API
2. `CUmodule`/`CULibrary` handling. Below is what's implemented in this PR:
| `cuda-python` version  | driver version | which to use | reason |
| ------------- | ------------- | ------------- | ------------- |
| 11.x | 11.x | `CUModule`  | only old symbols/APIs exist |
| 11.x | 12.x | `CUModule `  | binding does not expose the new symbols/APIs from the driver |
| 12.x | 11.x | `CUModule `  | driver does not support the new symbols/APIs |
| 12.x | 12.x | `CULibrary`   | both old/new can be used, prefer the new ones for [contextless support](https://developer.nvidia.com/blog/cuda-context-independent-module-loading/) |
> Support JIT compilation for CUDA driver & bindings 11.x

- cuda_core/tests/test_module.py
Module loading in 11.x tries to validate the module image upon load. Trivial dummy module data will error out.
> Filter out module test from cuda-python 11.x versions

- cuda_bindings/pyproject.toml
- cuda_bindings/setup.py
This PR adopts the same auto-discovery style as the cuda.core counterpart. This amendment is assured to expose the same data file as the posted Linux 12.6.2 patch. The change in style assist in getting most of the Windows files through.
Know issue: Windows builds can't auto-discover the trampoline files and they remain omitted from the final distributable. Note that Linux with this change does not face the same issue.
> Use pyproject for auto discovery of packages and data

- cuda_core/cuda/core/experimental/_device.py
- cuda_core/cuda/core/experimental/_event.py
- cuda_core/cuda/core/experimental/_launcher.py
- cuda_core/cuda/core/experimental/_memory.py
- cuda_core/cuda/core/experimental/_module.py
- cuda_core/cuda/core/experimental/_program.py
- cuda_core/cuda/core/experimental/_stream.py
- cuda_core/docs/source/_templates/autosummary/class.rst
- cuda_core/docs/source/_templates/autosummary/dataclass.rst
- cuda_core/docs/source/_templates/autosummary/namedtuple.rst
- cuda_core/docs/source/api.rst
- cuda_core/docs/source/api_private.rst
- cuda_core/docs/source/conf.py
- cuda_core/docs/source/install.md
- cuda_core/docs/source/release/0.1.0-notes.md
- cuda_python/docs/environment-docs.yml
Use [NumPy Style Python Docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) to maintain consistency with cuda-bindings.
Edit:
Close #96 
Close #207
> Docstrings for cuda.core

- cuda_bindings/MANIFEST.in
- cuda_bindings/pyproject.toml
> Fix discovery for trampoline files

- README.md
- cuda_bindings/README.md
- cuda_bindings/tests/test_nvjitlink.py
- cuda_core/README.md
- cuda_core/cuda/core/experimental/_stream.py
- cuda_python/docs/source/index.rst
add the ptx test. Was previously TODO
(cuda_py) ksimpson@NV-3KWHSV3:~/cuda-python/cuda-python/cuda_bindings/tests$ python -m pytest test_nvjitlink.py
=================================================================== test session starts ====================================================================
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/ksimpson/cuda-python/cuda-python/cuda_bindings
configfile: pyproject.toml
plugins: benchmark-4.0.0
collected 11 items
test_nvjitlink.py ...........  [100%]
> update the nvjitlink bindings test

- .github/copy-pr-bot.yaml
- .github/workflows/gh-build-and-test.yml
- use a smaller CPU runner for building the packages (closes #264)
- enforce manual CI triggering for all cases
> Some CI tweaks

- cuda_core/docs/source/index.rst
- cuda_core/docs/source/interoperability.rst
> Add an doc page for interoperatibility

- .github/actions/build/action.yml
- cuda_core/DESCRIPTION.rst
- cuda_core/README.md
- cuda_core/docs/source/install.md
- cuda_core/docs/source/release/0.1.1-notes.md
- cuda_core/pyproject.toml
> Prepare for wheel release + populate PyPI page information

- cuda_core/cuda/core/experimental/_memoryview.pyx
Close #285.
xref: https://github.com/NVIDIA/cuda-python/issues/285#issuecomment-2539868705
> Fix `StridedMemoryView` by deferring the check for whether a capsule is versioned

- cuda_core/tests/test_event.py
Event might not have yet completed when a synchronize is skipped
> Fix test_is_done without a sync

- .github/workflows/triagelabel.yml
Close #110.
For now we just need a working workflow. The skip condition is made as simple as checking if any label exists. It could be made more complex if any of us has more time.
> Fix triagelabel workflow

- .github/workflows/gh-build-and-test.yml
- cuda_core/examples/saxpy.py
- cuda_core/examples/strided_memory_view.py
- cuda_core/examples/vector_add.py
- cuda_core/tests/requirements-cu11.txt
- cuda_core/tests/requirements-cu12.txt
This is the second attempt of adding CuPy as an optional test dependency (https://github.com/NVIDIA/cuda-python/commit/4494a276d44177e68333a2cba21a35797d28c013). Previously we could not do it because `cupy.random.random()` APIs (used in code samples) require cuRAND to exist and I did not want to inflate the cached CTK sizes. This PR switches to use the new random number generator, which does not require cuRAND (host library). It also has an additional benefit that we teach users to not use the legacy random APIs.
An example bug on CUDA 11 is exposed as a result of this PR, which is also fixed (https://github.com/NVIDIA/cuda-python/pull/334#discussion_r1899253950).
> Add back CuPy as an optional test dependency + Fix an example bug

- cuda_core/cuda/core/experimental/_linker.py
close #303
Add a warning when we fall back to cuLink
> add warning to the nvjitlink ctor when falling back to cuLink

- .github/workflows/build-and-test.yml
The CI on main failed: https://github.com/NVIDIA/cuda-python/actions/runs/12587535835/job/35083892418, because it needs a write permission for content: https://github.com/JamesIves/github-pages-deploy-action#getting-started-airplane
> Fix doc ci permissions

- .github/actions/fetch_ctk/action.yml
- .github/copy-pr-bot.yaml
- .github/workflows/build-and-test.yml
Close #275. Close #131.
The CI infra is a stripped-down version of what's in the main branch today, the diff of which can be examined via:
https://github.com/NVIDIA/cuda-python/compare/main..leofang:cuda-python:ci_ctk11
(only focus on the `.github` folder; the remaining diff is noise and irrelevant for this PR).
> Backport: minimal CI infra for building & testing 11.8.x

- cuda_bindings/setup.py
Since each cpp is only used by a single extension, a simple solution is to expand the regex pattern and specify which extension uses it directly. Both private and utils have limited number of pyx files and therefore this regex expansion doesn't bloat either.
close #271
> Explicitly state which extension uses cpp files

- cuda_bindings/cuda/bindings/_bindings/cynvrtc.pyx.in
- cuda_bindings/docs/source/release/12.x.y-notes.md
- cuda_bindings/pyproject.toml
- cuda_bindings/setup.py
Support discovery of NVRTC and nvJitLink libraries at run time
CTK installations distribute their libraries using personal packages:
- nvidia-nvjitlink-cuXX
- nvidia-cuda-nvrtc-cuXX
The relative path of their libraries to cuda-bindings is consistent,
and allows us to use relative paths to discover them when loading
at run time.
close #286
close #287
> Enable discovery and loading at run time of NVRTC and nvJitLink libraries in a wheels ecosystem

- .github/actions/fetch_ctk/action.yml
- .github/workflows/build-and-test.yml
- cuda_bindings/tests_cython/build_tests.sh
- cuda_bindings/tests_cython/test_ccuda.pyx
- cuda_bindings/tests_cython/test_ccudart.pyx
- cuda_bindings/tests_cython/test_interoperability_cython.pyx
> [Backport] Enable Cython tests for `cuda.bindings`

- .github/workflows/backport.yml
- .github/workflows/build-and-test.yml
- .github/workflows/status-check.yml
> Add CI status check

- .github/workflows/build-and-test.yml
- .github/workflows/status-check.yml
> [Backport] Add CI Status check

- .github/workflows/build-and-test.yml
Manual backport of #368 to cope with workflow difference. Also PRs that touch the workflow files cannot be auto-backported (#365).
> [Backport] Test against CUDA wheels

- .github/workflows/build-and-test.yml
- .github/workflows/build-docs.yml
- .github/workflows/test-wheel.yml
- .github/workflows/test_local_ctk.yml
- cuda_core/tests/requirements-cu11.txt
- cuda_core/tests/requirements-cu12.txt
Close #367.
For detail see https://github.com/NVIDIA/cuda-python/pull/368#issuecomment-2580951092 below.
> Test against CUDA wheels

- .github/workflows/build-and-test.yml
- cuda_python/pyproject.toml
- cuda_python/setup.py
Backport [6bb7c0b](https://github.com/NVIDIA/cuda-python/pull/356/commits/6bb7c0bca962778751aff459783b1844b8244f49) from #356.
> [Backport] Add `cuda-python[all]` for passing through

- cuda_bindings/README.md
- cuda_bindings/docs/source/install.md
- cuda_core/README.md
> Document header requirements for Cython users

- .pre-commit-config.yaml
Closes #255 
This PR adds a `ci:` section to the pre-commit config. [pre-commit.ci](https://pre-commit.ci/) has been enabled for this repository.
> Add pre-commit.ci config

- .github/workflows/backport.yml
This PR contains 2 fixes, both due to me misreading the documentation 😛 
1. I noticed the `conflict_resolution` argument causes a warning because it's an experimental feature of the backport action, and it should not be passed directly as a input argument, but as a part of json.
https://github.com/korthout/backport-action#conflict_resolution
2. I've noticed the backport workflow went nuts in a few recently-merged PRs, where the backport step is triggered even if the PR does not have the `to-be-backported` label, ex: https://github.com/NVIDIA/cuda-python/pull/372#issuecomment-2591809508. It turns out that `label_pattern` is meant to be used [as a way to find the backport branch](https://github.com/korthout/backport-action#how-it-works) (for which we already set `target_branch`), not the …
> CI: Fix backport workflow

- cuda_bindings/cuda/bindings/_lib/cyruntime/cyruntime.pyx.in
close #101
This was the only conversion warning.
> Explicitly convert to cuuint64_t*

- .github/actions/doc_preview/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/build-docs.yml
Close #346.
This PR adds a new `doc_preview` action that deploys docs built in each PR to 
```
https://nvidia.github.io/cuda-python/pr-preview/pr-<id>/
```
and post a message. Upon PR merge, the action would clean up the pushed files to remove the preview.
The `doc_preview` largely follows the logic of [`pr-preview-action`](https://github.com/rossjrw/pr-preview-action/), but has to be re-implemented to cope with two limitations:
1. Our copy-pr-bot can only be triggered by a `push` event, not by `pull_request` or `pull_request_target` events as required by `pr-preview-action`
2. The upstream `pr-preview-action` has no plan to support taking a PR number as an input parameter to bypass the first limitation (see https://github.com/NVIDIA/cuda-python/pull/380#issuecomment-2588834001)
It is …
> Add doc preview CI

- .github/workflows/build-and-test.yml
- README.md
- cuda_bindings/DESCRIPTION.rst
- cuda_bindings/README.md
- cuda_bindings/pyproject.toml
- cuda_core/README.md
> Add project description

- .github/actions/doc_preview/action.yml
Follow-up of #395. This is needed because the way we build component docs could make it a bit hard to navigate when previewing the changes.
> Improve doc CI comment 

- .github/actions/get_pr_number/action.yml
- cuda_bindings/docs/source/conf.py
- cuda_core/docs/source/conf.py
- cuda_python/docs/source/conf.py
- cuda_python/pyproject.toml
Follow-up of #410. Turns out we broke the latest docs https://nvidia.github.io/cuda-python/latest/. This PR adds more fine-grained warning banners to fix it:
- When building the PR previews, the warning banner links back to the PR (this was done in #410)
- When merging into `main` and updating the latest docs, a new warning banner is added
> CI: Fix the latest docs with more fine-grained warning banners

- .github/workflows/release-upload.yml
- .github/workflows/release.yml
Backport of everything added up to #419. The only difference compared to the main branch is that the doc upload job was not backported.
> [Backport] CI: Add a release workflow

- .github/workflows/build-docs.yml
- .github/workflows/test-wheel.yml
The old runners are removed, so all CIs are blocked due to lack of runners.
> Update to use the new NVKS runners

- cuda_bindings/docs/build_docs.sh
- cuda_bindings/docs/source/overview.md
- cuda_core/docs/build_docs.sh
- cuda_python/docs/build_docs.sh
close #351
- `.doctrees` contain cached build files and don't impact html rendering. Store them outside of html build path.
- `overview.md` has page settings that triggers Jupyter notebook execution. Since the settings have minimal impact on displayed page, remove them to avoid hash regeneration.
> Stop tracking cached files and Jupyter notebook hashes in doc builds

- cuda_bindings/docs/source/api.rst
- cuda_bindings/docs/source/install.md
- cuda_bindings/docs/source/module/nvvm.rst
- cuda_bindings/docs/source/release.rst
- cuda_bindings/docs/source/release/11.8.7-notes.rst
- cuda_bindings/docs/source/release/12.X.Y-notes.rst
> Add cuda_bindings/docs/source/module/nvvm.rst

- cuda_core/cuda/core/experimental/_linker.py
The LinkerOptions were implemented before ProgramOptions, which uses an improved logic for handling optional sequence arguments. This review migrates the linker to that logic. It could present as a bug if someone was using the linker backed ptx program.
close #432
> Update linker options sequence handling

- cuda_bindings/examples/0_Introduction/clock_nvrtc_test.py
- cuda_bindings/examples/0_Introduction/simpleCubemapTexture_test.py
- cuda_bindings/examples/0_Introduction/vectorAddDrv_test.py
Modified `cuda_bindings/examples/0_Introduction/vectorAddDrv_test.py` to use `randn(N)` instead of `randn(size)`. Also renamed `size` to `nbytes` to readability.
Modified `clock_nvrtc_test.py` to improve readability.
> Improvements to some cuda bindings example

- cuda_core/cuda/core/experimental/_module.py
- cuda_core/cuda/core/experimental/_program.py
- cuda_core/tests/test_linker.py
- cuda_core/tests/test_module.py
Adds the ability to link multiple PTX files with one linker instance.
> Add `ObjectCode` ptx constructor

- cuda_core/cuda/core/experimental/_context.py
- cuda_core/cuda/core/experimental/_device.py
- cuda_core/cuda/core/experimental/_event.py
- cuda_core/cuda/core/experimental/_module.py
- cuda_core/cuda/core/experimental/_stream.py
- cuda_core/tests/test_context.py
- cuda_core/tests/test_device.py
- cuda_core/tests/test_event.py
- cuda_core/tests/test_module.py
- cuda_core/tests/test_stream.py
Contributes to #198
Make disabling `__init__` uniform across cuda.core:
* Use `@classmethod` as the only constructor: Best for strict enforcement.
* Uniform `raise RuntimeError()` with a standardized message form.
The starting point for this change was extracted from PR #458:
* https://github.com/NVIDIA/cuda-python/pull/458#issuecomment-2692862620
* https://github.com/NVIDIA/cuda-python/pull/458#issuecomment-2692875231
> Apply `__new__` approach to disabling `__init__`

- cuda_core/cuda/core/experimental/_device.py
- cuda_core/docs/source/release/0.2.0-notes.rst
- cuda_core/tests/test_device.py
Closes #485
Adds a method to the `Device` class which allows you to make an Event without immediately recording it to a Stream.
> NEW: Create an Event without recording to Stream

- cuda_core/cuda/core/experimental/_event.py
- cuda_core/docs/source/release/0.2.0-notes.rst
- cuda_core/tests/test_event.py
When working on #475 (68c93652eb4037af9c5755745668800566413689) I noticed we surprisingly haven't implemented event-based timing...  Looks like an oversight to me because we did spend a lot of time discussing the default of the `enabling_timing` option and how to retrieve the timing result. This PR adds the implementation, which is also aligned with the `cuda::experimental::timed_event` treatment: 
https://github.com/NVIDIA/cccl/blob/096596b3580d6cb2042fff692e8162d2a0ea356b/cudax/include/cuda/experimental/__event/timed_event.cuh#L90
> Add event timing

- cuda_core/cuda/core/experimental/_module.py
- cuda_core/tests/test_module.py
Weirdly I am not able to tag Michael or add him as reviewer. 
close #490
> add public handle to object code

- cuda_core/tests/test_event.py
Observed failures:
```
>           assert delay_seconds * 1000 <= elapsed_time_ms < delay_seconds * 1000 + 2  # tolerance 2 ms
E           assert 503.1598205566406 < ((0.5 * 1000) + 2)
```
```
>           assert delay_seconds * 1000 <= elapsed_time_ms < delay_seconds * 1000 + 2  # tolerance 2 ms
E           assert 505.0583190917969 < ((0.5 * 1000) + 2)
```
> Increase tolerance in `test_timing()` to avoid flaky tests.

- cuda_bindings/cuda/bindings/driver.pyx.in
- cuda_bindings/cuda/bindings/nvrtc.pyx.in
- cuda_bindings/tests/test_cuda.py
- cuda_bindings/tests/test_nvrtc.py
Manual backports of:
* #497
* #499
`cuKernelGetName` and `cuFuncGetName` do not exist on the 11.8.x branch.
> Backport #497 and #499

- cuda_core/tests/test_event.py
Observed:
```
> assert delay_ms <= elapsed_time_ms < delay_ms + generous_tolerance
E assert 500.0 <= 490.03173828125
test_event.py:41: AssertionError
```
The `generous_tolerance` also needs to be applied when checking the lower bound.
> Fix `test_timing` flakiness under Windows

- cuda_core/cuda/core/experimental/__init__.py
Downstream packages that want to use `Event` to type hint their APIs should be able to import `Event` without accessing private modules.
https://github.com/NVIDIA/cuda-python/issues/469#issuecomment-2707430036
I understand that `Event`s should not be constructed directly, but having `__new__()` raise a RuntimeError should be sufficient to prevent that.
> NEW: Add Event to public API

- cuda_core/cuda/core/experimental/_utils/cuda_utils.py
This one-line change results in a 8k+ fold speedup.
```
>>> 35.381859/0.004149
8527.804049168473
```
```
$ git stash
$ python test_slowness.py 100000
driver.cuDriverGetVersion() 12060
cuda_utils.get_binding_version() (12, 8)
driver.cuDriverGetVersion()
0.023946 seconds for 100000 iterations
0.24 µs per call
cuda_utils.get_binding_version()
35.381859 seconds for 100000 iterations
353.82 µs per call
```
```
$ git stash pop
$ python test_slowness.py 100000
driver.cuDriverGetVersion() 12060
cuda_utils.get_binding_version() (12, 8)
driver.cuDriverGetVersion()
0.022644 seconds for 100000 iterations
0.23 µs per call
cuda_utils.get_binding_version()
0.004149 seconds for 100000 iterations
0.04 µs per call
```
________
In retrospect, I should have just looked at the `get_bindings()` implementation …
> Add `@functools.lru_cache` decorator for `get_binding_version()`

- README.md
- cuda_python/docs/source/index.rst
I'm not sure if this helps move things in the right direction towards a clear and succinct summary of these two modules, but I'm interested in others' thoughts.
> [DOCS] Clarify that cooperative is for device, parallel for host

- cuda_bindings/cuda/bindings/cyruntime.pyx.in
- cuda_bindings/cuda/bindings/driver.pyx.in
- cuda_bindings/cuda/bindings/nvrtc.pyx.in
- cuda_bindings/cuda/bindings/runtime.pyx.in
> Move callback wrappers to Python layer

- cuda_bindings/cuda/bindings/driver.pyx.in
- cuda_bindings/cuda/bindings/nvrtc.pyx.in
- cuda_bindings/cuda/bindings/runtime.pyx.in
> fast error code

- README.md
- cuda_bindings/DESCRIPTION.rst
- cuda_bindings/README.md
- cuda_bindings/docs/build_docs.sh
- cuda_bindings/docs/source/conf.py
- cuda_bindings/docs/source/install.md
- cuda_bindings/docs/source/module/nvjitlink.rst
- cuda_bindings/docs/source/module/nvvm.rst
- cuda_bindings/docs/source/overview.md
- cuda_bindings/docs/source/release/11.8.7-notes.rst
- cuda_bindings/docs/source/release/12.X.Y-notes.rst
- cuda_core/docs/source/install.md
- cuda_python/docs/source/conf.py
- cuda_python/docs/source/index.rst
- Close #532
- Close #537
- Fix #522 (which mixed up `cuda.cooperative` and `cuda.parallel`)
- Improve cuda.core/bindings installation guides
- Add missing release note entries
- Consolidate `cuda.bindings` installation instructions 
- Fix hyperlinks to nvJitLink/NVVM API references 
- Misc fixes
> Various documentation improvements 

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/doc_request.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
Adds pull request and issue templates copied and adapted from CCCL
> Add pull request and issue templates copied from CCCL

- .github/workflows/bandit.yml
- .github/workflows/codeql.yml
- .pre-commit-config.yaml
Resolves #534
Adds scans using both CodeQL and Bandit. Could use some discussion on what level of reporting we wish to have here and when we want to error. I have updated the repo settings to alert on any Security alert severity level and set the Standard alert severity level to "Errors and warnings" as a starting point.
> Add CodeQL and Bandit Static Analysis Scans

- cuda_bindings/cuda/bindings/driver.pyx.in
- cuda_bindings/cuda/bindings/nvrtc.pyx.in
- cuda_bindings/cuda/bindings/runtime.pyx.in
- cuda_bindings/docs/source/release/12.X.Y-notes.rst
- cuda_bindings/tests/test_cuda.py
closes #561 
Failed API calls return None for non error code tuple elements
> Return None values when API errors

- cuda_bindings/cuda/bindings/_bindings/cynvrtc.pyx.in
- cuda_bindings/cuda/bindings/_internal/nvvm_windows.pyx
- cuda_bindings/setup.py
> [Backport] Fix support for NVVM from conda on Windows + other fixes

- .github/actions/fetch_ctk/action.yml
Makes API changes to the local fetch_ctk GitHub action, so that non-admin developers can choose which CTK components are installed into the environment.
The hash of the string of the provided CTK components is now appended to the filename so that changing the components will be a cache miss.
closes https://github.com/NVIDIA/cuda-python/issues/571
~~- [ ] New or existing tests cover these changes.~~
~~- [ ] The documentation is up to date with these changes.~~
There are no tests for the CI, and although I have added a description to the new parameter, there are no docs for the CI?
> CI: Remove fetch_ctk component hardcoding and add hash to filename

- .bandit
- .pre-commit-config.yaml
- cuda_bindings/tests/test_cuda.py
- cuda_core/tests/example_tests/utils.py
- cuda_python/setup.py
When #560 added Bandit, it didn't fix the existing issues in the codebase that Bandit flags. This fixes the issues and skips them where the fixes are non-trivial and the underlying issue is relatively innocuous.
Additionally, adds a `.bandit` configuration file to the root of the repo that bandit will use by default and tells pre-commit to use that configuration file as well.
> Add bandit config, fix failing issues

- cuda_core/cuda/core/experimental/_event.py
- cuda_core/cuda/core/experimental/_linker.py
- cuda_core/cuda/core/experimental/_memory.py
- cuda_core/cuda/core/experimental/_module.py
- cuda_core/cuda/core/experimental/_program.py
- cuda_core/cuda/core/experimental/_stream.py
Adds caution admonition to documentation for users who are accessing the handle property of cuda.core objects. The alternative was to add a docstring for __int__() for the cuda.bindings python objects. However, these python objects are autogenerated, and I couldn't see where the bindings were generated from. There's just text at the top of all the pyx files that state the bindings are autogenerated and that they should not be manually edited.
closes https://github.com/NVIDIA/cuda-python/issues/557
> DOC: Add admonition to docstrings for cuda.core handle properties

- .github/workflows/test-wheel-linux.yml
- cuda_bindings/docs/source/environment_variables.md
- cuda_bindings/tests/conftest.py
- cuda_bindings/tests/test_cuda.py
- cuda_bindings/tests/test_cudart.py
- cuda_core/tests/conftest.py
- cuda_core/tests/test_cuda_utils.py
- cuda_core/tests/test_event.py
- cuda_core/tests/test_linker.py
Runs python 3.12 pytests in the context of [compute-sanitizer](https://docs.nvidia.com/compute-sanitizer/ComputeSanitizer/index.html#about-compute-sanitizer) to check for memory issues and errors from the CUDA API. 
closes https://github.com/NVIDIA/cuda-python/issues/565
closes https://github.com/NVIDIA/cuda-python/issues/562
> CI: Run some tests with compute-sanitizer

- CONTRIBUTING.md
- cuda_bindings/DESCRIPTION.rst
- cuda_bindings/README.md
- cuda_core/DESCRIPTION.rst
- cuda_core/README.md
- cuda_python/DESCRIPTION.rst
- cuda_python/pyproject.toml
closes #300
- Designates DESCRIPTION.rst files for pypi package description. They describe the package and provide forwards users to further documentation using links.
- Designates README.md as a more in-depth description of the pages. In addition to providing the package description and documentation links, it also mentions development practices and running tests.
- Moves shared project development practices to CONTRIBUTING.md
- Omits linter changes since that will be covered in #581
> Consolidate shared info between README.md and DESCRIPTION.rst

- .github/actions/fetch_ctk/action.yml
We want to always use the latest compute-sanitizer because there could be bug fixes for the compute-sanitizer, and it is OK to use the newest compute-sanitizer on programs running with old CTK versions.
closes #594
> CI: Always fetch the compute-sanitizer from the CTK 12.8.1

- .github/actions/fetch_ctk/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/test-wheel-windows.yml
> Ensure `fetch_ctk` action can be used everywhere

- .github/workflows/test-wheel-linux.yml
- .github/workflows/test-wheel-windows.yml
Switch to use the workflow file name as the name is getting missed in the merged code in main. Verified the behavior locally too. This is a follow up from #555 addressing an issue seen after merging.
> CI: Reference workflow file name for old branch

- cuda_bindings/cuda/bindings/_path_finder/README.md
- cuda_bindings/cuda/bindings/_path_finder/load_dl_windows.py
- cuda_bindings/tests/run_python_code_safely.py
- cuda_bindings/tests/spawned_process_runner.py
- cuda_bindings/tests/test_path_finder_load.py
- cuda_bindings/tests/test_spawned_process_runner.py
* commit 048e689e5a4cdf2f6c3edb4a38b1c19d37cef309: as discussed with @leofang offline
* commit d539b4337bfe056e1ef028856bb9efd6a1a33e86: addresses https://github.com/NVIDIA/cuda-python/pull/604#discussion_r2075856805
* All other commits: address https://github.com/NVIDIA/cuda-python/pull/604#discussion_r2075888141 and concerns about using `exec`
> Miscellanous path_finder cleanup post release

- .github/actions/fetch_ctk/action.yml
Currently we do not need any `LD_LIBRARY_PATH` or `PATH` manipulations for `nvvm` in any of our testing environments.
Possible explanation (I have NOT verified this): Either `nvvm` is installed via a Python wheel, or `CUDA_HOME` is set.
> Remove nvvm-related `LD_LIBRARY_PATH`, `PATH` manipulations in fetch_ctk action.

- CONTRIBUTING.md
- LICENSE.md
- cuda_bindings/docs/source/release.rst
- cuda_bindings/docs/source/release/12.8.0-notes.md
- cuda_bindings/docs/source/release/12.9.0-notes.rst
- cuda_bindings/docs/source/release/12.X.Y-notes.rst
- cuda_python/docs/source/release.md
- cuda_python/docs/source/release/12.8.0-notes.md
- cuda_python/docs/source/release/12.X.Y-notes.rst
closes https://github.com/NVIDIA/cuda-python/issues/476
> Address remaining OSRB requests + document known installation issues

- cuda_core/cuda/core/experimental/_module.py
- cuda_core/docs/source/release/0.3.0-notes.rst
- cuda_core/tests/conftest.py
- cuda_core/tests/test_module.py
closes #568 
This PR implements `Kernel.num_arguments` and `Kernel.argument_info` properties:
- `Kernel.num_arguments` returns the number of arguments in the kernel instance
- `Kernel.argument_info` returns a list of tuples `(offset, size)` which describes layout of the struct containing all kernel arguments,
> Implement Kernel.num_arguments, and Kernel.arguments_info

- .github/actions/doc_preview/action.yml
- .github/actions/fetch_ctk/action.yml
- .github/actions/get_pr_number/action.yml
- .github/dependabot.yml
- .github/workflows/backport.yml
- .github/workflows/build-docs.yml
- .github/workflows/build-wheel.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/release-upload.yml
- .github/workflows/release.yml
- .github/workflows/status-check.yml
- .github/workflows/test-wheel-linux.yml
- .github/workflows/test-wheel-windows.yml
- cuda_bindings/pyproject.toml
- cuda_bindings/tests/cython/build_tests.sh
- cuda_core/tests/cython/build_tests.sh
- close #525
- close #466 
- close #639
- close #644
- tentatively pin at cython<3.1.0 (#642)
Previously, the Cython tests are run on
- Latest CUDA 11.x (11.8.0) and 12.x (12.9.0)
- Linux only 
With this PR, the Cython tests are run on
- Latest CUDA 12.x (12.9.0)
- Linux and Windows
We can no longer run against the previous major version because of the way of building the Cython tests is changed. It is now built against the build-time CTK, which is always the latest major.minor. But I think this is OK, because the same Cython tests are already run in each major version's branch ([example from 11.x](https://github.com/NVIDIA/cuda-python/blob/e290d52b779daff9961c3c18e30633a0052a31ea/.github/workflows/build-and-test.yml#L317)).
There is still one open task relevant to Cython tests …
> Always build and run Cython tests + other CI improvements 

- cuda_core/cuda/core/experimental/_device.py
- cuda_core/cuda/core/experimental/_event.py
- cuda_core/cuda/core/experimental/_stream.py
- cuda_core/docs/source/release/0.3.0-notes.rst
- cuda_core/tests/test_event.py
> Implement device and context properties for Event

- cuda_core/cuda/core/experimental/_module.py
- cuda_core/tests/test_module.py
Closes https://github.com/NVIDIA/cuda-python/issues/526
> Enable serialization/deserialization of `ObjectCode` instances

- cuda_bindings/tests/test_nvjitlink.py
To minimize distractions while debugging, e.g. when upgrading to newer CTK versions.
Before this PR:
```
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.5, pluggy-1.6.0 -- /home/rgrossekunst/forked/cuda-python/venvs/scratch/bin/python
cachedir: .pytest_cache
benchmark: 5.1.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/rgrossekunst/forked/cuda-python/cuda_bindings/tests
configfile: pytest.ini
plugins: benchmark-5.1.0
collecting ... collected 35 items
tests/test_nvjitlink.py::test_unrecognized_option_error PASSED           [  2%]
tests/test_nvjitlink.py::test_invalid_arch_error PASSED …
```
> Make `test_nvjitlink.py` less noisy.

- cuda_core/cuda/core/experimental/_kernel_arg_handler.pyx
- cuda_core/docs/source/release/0.3.0-notes.rst
- cuda_core/tests/test_launcher.py
closes #260.
The test coverage revealed a bug in the fp16 scalar handling. The existing handling is obviously wrong and it's me to blame, but I honestly can't recall why I believed the code was correct 😞
> Add tests to cover scalar handling in `launch()` + Fix fp16 bug

- .github/workflows/build-wheel.yml
Update the base image for the Windows-based CI builds from `windows-2019` to `windows-2022`, closes #665.
The `windows-2019` image has been deprecated and will be removed at the end of June 2025. Move to `windows-2022` and verify everything builds as expected.
> Migrate to `windows-2022` for Windows CI builds

- cuda_bindings/cuda/bindings/_internal/nvvm.pxd
- cuda_bindings/cuda/bindings/_internal/nvvm_linux.pyx
- cuda_bindings/cuda/bindings/_internal/nvvm_windows.pyx
- cuda_bindings/cuda/bindings/cynvvm.pxd
- cuda_bindings/cuda/bindings/cynvvm.pyx
- cuda_bindings/cuda/bindings/nvvm.pxd
- cuda_bindings/cuda/bindings/nvvm.pyx
- cuda_bindings/tests/test_nvvm.py
Closes #683
Fix a minor accidental omission.
> Add missing `nvvmGetErrorString()` bindings.

- cuda_bindings/tests/test_nvjitlink.py
Discovered while working on upgrades.
Without this change, `get_dummy_ltoir` returned an empty `bytes` object (`b''`) instead of raising an exception.
Using the opportunity to improve the error message:
```diff
-            raise RuntimeError(f"Nvrtc Error: {err}")
+            raise RuntimeError(repr(err))
```
Before:
```
RuntimeError: Nvrtc Error: 7
```
After:
```
RuntimeError: <nvrtcResult.NVRTC_ERROR_BUILTIN_OPERATION_FAILURE: 7>
```
> Add missing NVRTC error handling in `test_nvjitlink.py:get_dummy_ltoir()`

- ci/tools/setup-sanitizer
- cuda_bindings/docs/source/environment_variables.md
- cuda_bindings/tests/conftest.py
- cuda_bindings/tests/test_cuda.py
- cuda_bindings/tests/test_cudart.py
- cuda_core/tests/conftest.py
- cuda_core/tests/test_cuda_utils.py
- cuda_core/tests/test_event.py
- cuda_core/tests/test_linker.py
- cuda_core/tests/test_module.py
We rely on driver/runtime to report API errors to us for decision making and input checking (https://github.com/NVIDIA/cuda-python/issues/685). If the compute-sanitizer keeps treating API errors as real errors, we end up skipping the majority of the test suite. Before the sanitizer can suppress errors on a per-API basis, we turn `--report-api-errors` off globally.
> Make compute-sanitizer not report API errors as errors

- README.md
- cuda_python/docs/source/conf.py
- cuda_python/docs/source/index.rst
- cuda.coop & cuda.par are merged into cuda.cccl
- emphasize the versatile roles of nvmath-python
> Update the notes on the CCCL and nvmath-python projects

- cuda_core/cuda/core/experimental/_kernel_arg_handler.pyx
- cuda_core/examples/memory_ops.py
- cuda_core/tests/test_launcher.py
Buffers allocated using the `LegacyPinnedMemoryResource` have , but the kernel param handler doesn't know how to handle these buffers. This PR fixes that.
Closes #715
> Ensure correct handling of buffers allocated with `LegacyPinnedMemoryResource.allocate` as kernel parameters

- ci/tools/run-tests
- cuda_core/cuda/core/__init__.py
- cuda_core/docs/source/api.rst
- cuda_core/docs/source/getting-started.md
- cuda_core/docs/source/index.rst
- cuda_core/examples/cuda_graphs.py
- cuda_core/examples/jit_lto_fractal.py
- cuda_core/examples/pytorch_example.py
- cuda_core/examples/saxpy.py
- cuda_core/examples/show_device_properties.py
- cuda_core/examples/simple_multi_gpu_example.py
- cuda_core/examples/strided_memory_view_cpu.py
- cuda_core/examples/strided_memory_view_gpu.py
- cuda_core/examples/thread_block_cluster.py
- cuda_core/examples/vector_add.py
- cuda_core/pyproject.toml
Closes #570.
Merge after #717 
* This PR adds a "getting started" page that explains what `cuda.core` is, walks through one of our simpler examples, and links to the examples directory. It's not a comprehensive introduction to `cuda.core`, but it's a start.
* Also fixes up our dependencies so that the getting started example works out of the box.
* Also adds a graph capture example as that seemed missing.
> Add a "Getting Started" page to the documentation

- cuda_core/tests/test_launcher.py
cuda_core is generally set up to run most tests without `cupy` installed.
PR #717 added one unconditional `cupy` import. This PR adopts the approach in `tests/test_utils.py` for the import in `tests/test_launcher.py`, and copies the `SKIPPED` message from `tests/example_tests/utils.py`.
> Restore option to run testing without cupy installed.

- .gitignore
- cuda_bindings/cuda/bindings/utils/__init__.py
- cuda_bindings/cuda/bindings/utils/_get_handle.pyx.in
- cuda_bindings/docs/source/module/utils.rst
- cuda_bindings/docs/source/release/12.X.Y-notes.rst
- cuda_bindings/docs/source/tips_and_tricks.rst
- cuda_bindings/setup.py
- cuda_bindings/tests/test_utils.py
closes #564
The performance is comparable to the existing `int()` approach (O(10) ns):
```python
In [1]: from cuda.bindings import driver
In [3]: s = driver.CUstream(1234)
In [4]: int(s)
Out[4]: 1234
In [6]: from cuda.bindings.utils import get_cuda_native_handle
In [7]: get_cuda_native_handle(s)
Out[7]: 1234
In [8]: %timeit int(s)
44.7 ns ± 1.34 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
In [9]: %timeit get_cuda_native_handle(s)
95.1 ns ± 1.06 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```
> Add `get_cuda_native_handle`

- cuda_pathfinder/cuda/pathfinder/_dynamic_libs/load_dl_linux.py
- cuda_pathfinder/cuda/pathfinder/_dynamic_libs/load_dl_windows.py
- cuda_pathfinder/cuda/pathfinder/_dynamic_libs/load_nvidia_dynamic_lib.py
Closes #763
This fixes the issue, but corresponding new tests are missing.
> [pathfinder] Fix #763 (load `libnvJitLink.so.12` from conda, not `/usr/local/cuda`)

- cuda_bindings/tests/cufile.json
- cuda_bindings/tests/test_cufile.py
> Add logic to skip WSL tests and add cufile.json for async tests

- cuda_bindings/site-packages/_cuda_bindings_redirector.py
Avoid premature import of `cuda.bindings` in redirector to fix startup noise (see [here](https://github.com/NVIDIA/cuda-python/pull/773#issuecomment-3111270268)).
Previously, the `_cuda_bindings_redirector.py` file imported `cuda.bindings` at interpreter startup to ensure the `cuda` namespace was initialized. However, this triggered early loading of Cython modules that depend on `win32api`, which may not be available yet due to `.pth` file processing order.
This commit replaces `import cuda.bindings` with `import cuda`, which is sufficient to ensure the `cuda` namespace is in `sys.modules`. The version redirect via `cuda.__version__` is preserved by assigning a custom `LazyCudaModule` type to `sys.modules["cuda"]`.
As a result, `cuda.__version__` continues to work (with a deprecation …
> _cuda_bindings_redirector.py fix (made necessary by PR #773)

- README.md
- SECURITY.md
- cuda_core/README.md
- cuda_core/docs/source/getting-started.md
This PR fixes multiple documentation and comment issues across the codebase to improve consistency, clarity, and correctness:
- Corrects spelling errors (`transfering` → `transferring`, `absense` → `absence`)
- Fixes capitalization (`pythonic` → `Pythonic`)
- Improves grammar (`re-structured` → `restructured`, `bring up` → `introduce`)
- Fixes subject-verb agreement (`list interfaces are` → `is`)
- Standardizes terminology (`meta package` → `metapackage`)
- Corrects incorrect verb forms (`Setup` → `Set up`)
- Fixes directory path typos (`test/cython` → `tests/cython`)
- Improves preposition usage (`against` → `with installations`)
These changes are non-functional and only affect text comments, documentation, and user-facing strings.
closes 
- [N/A] New or existing tests cover these …
> Fix typos and grammar in documentation

- README.md
- cuda_python/DESCRIPTION.rst
- cuda_python/docs/source/conf.py
- cuda_python/docs/source/index.rst
https://nvidia.github.io/cccl/cuda_cooperative/ and https://nvidia.github.io/cccl/cuda_parallel/ are 404s
Update to pages under https://nvidia.github.io/cccl/python/
> Let me know if opening a github issue is necessary just for this
> My main dev machine with my gpg key for signing is down with power outage in our office, I'll resign and push tomorrow if that's required.
> Fix URLs for cccl docs

- cuda_bindings/cuda/bindings/_internal/cufile.pxd
- cuda_bindings/cuda/bindings/_internal/cufile_linux.pyx
- cuda_bindings/cuda/bindings/cufile.pxd
- cuda_bindings/cuda/bindings/cufile.pyx
- cuda_bindings/cuda/bindings/cycufile.pxd
- cuda_bindings/cuda/bindings/cycufile.pyx
Some APIs added with CTK 13 are still missing:
* `cuFileSetParameterSizeT`
* `cuFileSetParameterBool`
* `cuFileSetParameterString`
* `cuFileDriverClose`
* `cuFileGetParameterMinMaxValue`
* `cuFileSetStatsLevel`
* `cuFileGetStatsLevel`
* `cuFileStatsStart`
* `cuFileStatsStop`
* `cuFileStatsReset`
* `cuFileGetStatsL1`
* `cuFileGetStatsL2`
* `cuFileGetStatsL3`
* `cuFileGetBARSizeInKB`
* `cuFileSetParameterPosixPoolSlabArray`
* `cuFileGetParameterPosixPoolSlabArray`
These will be worked on separately.
> Minimal cufile cuda_bindings updates for CTK 13

- .github/workflows/build-wheel.yml
- cuda_bindings/setup.py
Both CUDA_HOME (or CUDA_PATH) and LIBRARY_PATH are required to be set in the environment during installation. There was already a check for CUDA_HOME in setup.py, but no check for LIBRARY_PATH. This change adds a check to make sure LIBRARY_PATH is set.
When LIBRARY_PATH is not set, the installation fails at link time and indicates that cudart_static could not be found.
> Adds path for the CUDA static library based on CUDA_HOME

- cuda_core/cuda/core/experimental/_graph.py
While working on C++ stand-alone code executing what `test_graph.py` does in gh-843, I noticed that `add_child` passes dependendencies extracted from capturing stream inconsistently with num_dependencies parameter obtained in the same cuStreamGetCaptureInfo call.
Incidentally, after correcting this error, I can no longer reproduce errors reported in gh-843
closes #843
> Fix an apparent mistake in GraphBuilder.add_child

- cuda_bindings/cuda/bindings/_bindings/cydriver.pyx.in
- cuda_bindings/cuda/bindings/_bindings/cynvrtc.pyx.in
- cuda_bindings/cuda/bindings/_bindings/cyruntime.pyx.in
- cuda_bindings/docs/source/release/13.X.Y-notes.rst
This reduces the calling overhead of binding functions that require `cuPythonInit` or `cudaPythonInit` to be called.
This reduces the time it takes to call `driver.cuDeviceGet(0)` (for example) by about 50ns (on my machine):
- Base: Mean +- std dev: 149 ns +- 8 ns
- This PR: Mean +- std dev: 101 ns +- 2 ns
Note that these times include the work done by the actual underlying `cuDeviceGet` call, not just the function call overhead.
The `cuPythonInit` function is extremely large, so no C compiler is likely to ever inline it.  By creating a small wrapper function just to check the `init` flag and then delegate to the big function, the C compiler inlines it.  This not only removes a C function call, but probably helps out the branch predictor when checking the flag.
closes
> Reduce overhead of bindings requiring `cuPythonInit()`

- .github/dependabot.yml
- cuda_bindings/docs/source/release/13.X.Y-notes.rst
Update Dependabot configuration to reduce update churn.
Changes
* Switch schedule from weekly to monthly (9:00 PT).
* Limit to one open PR at a time.
* Add a group rule to bundle all minor/patch GitHub Actions updates into a single monthly PR.
This should cut down on review noise while still keeping dependencies reasonably up to date.
___
Piggy-backed: Fix existing (on `main`) pre-commit error
> Dependabot: consolidate GitHub Actions updates to monthly

- cuda_bindings/cuda/bindings/_bindings/cydriver.pyx.in
- cuda_bindings/cuda/bindings/_bindings/cynvrtc.pyx.in
- cuda_bindings/cuda/bindings/_bindings/cyruntime.pxd.in
- cuda_bindings/cuda/bindings/_bindings/cyruntime.pyx.in
This just commits to main the results from the latest version of the generator that are whitespace only.  I think we got in this state because some "written by hand" changes to the generated code were merged, and then the ports to the generator didn't match that exactly.  While none of these changes should have any effect, this will just help future runs of the generator apply cleanly.
> Update with whitespace-only changes from cython-gen

- .github/workflows/build-wheel.yml
- cuda_pathfinder/DESCRIPTION.rst
- cuda_pathfinder/cuda/pathfinder/_version.py
- cuda_pathfinder/docs/nv-versions.json
- cuda_pathfinder/docs/source/release.rst
- cuda_pathfinder/docs/source/release/1.2.0-notes.rst
- cuda_pathfinder/pyproject.toml
Closes #761
`cuda_pathfinder/DESCRIPTION.rst` is referenced in `cuda_pathfinder/pyproject.toml` for some time, but due to an oversight it was never added to the repo.
Bump cuda-pathfinder version to `1.2.0` for release.
> Add `cuda_pathfinder/DESCRIPTION.rst` and prepare for `v1.2.0` release

- cuda_bindings/cuda/bindings/_lib/utils.pxi.in
- cuda_bindings/cuda/bindings/driver.pxd.in
- cuda_bindings/cuda/bindings/driver.pyx.in
- cuda_bindings/cuda/bindings/nvrtc.pyx.in
- cuda_bindings/cuda/bindings/runtime.pxd.in
- cuda_bindings/cuda/bindings/runtime.pyx.in
- cuda_bindings/pyproject.toml
- cuda_core/cuda/core/experimental/_linker.py
- cuda_core/cuda/core/experimental/_memory.pyx
- cuda_core/cuda/core/experimental/_program.py
- cuda_core/cuda/core/experimental/_stream.pyx
- cuda_core/cuda/core/experimental/_system.py
- cuda_core/pyproject.toml
- cuda_core/tests/test_memory.py
closes #891 
This is a replacement for #892 (it was easier to rebase by hand than get Copilot to do it...)
> Fix #891: Use built-in types rather than typing aliases for type annotations

- .github/workflows/test-wheel-windows.yml
Migrate the Windows testing to use the new NV GHA runners.
> CI: Move to self-hosted Windows GPU runners

- cuda_bindings/cuda/bindings/driver.pyx.in
- cuda_bindings/cuda/bindings/runtime.pyx.in
This PR implements proper None checks using `is`/`is not`, contains code regenerated from https://github.com/NVIDIA/cuda-python-private/pull/146.
> refactor: replace none equality checks with `is`/`is not` equivalents

- cuda_bindings/cuda/bindings/_internal/cufile_linux.pyx
- cuda_bindings/cuda/bindings/_internal/nvjitlink_linux.pyx
- cuda_bindings/cuda/bindings/_internal/nvjitlink_windows.pyx
- cuda_bindings/cuda/bindings/_internal/nvvm_linux.pyx
- cuda_bindings/cuda/bindings/_internal/nvvm_windows.pyx
> Fix #962: Don't perform unnecessary version checks

- cuda_bindings/cuda/bindings/_lib/windll.pxd
- cuda_bindings/cuda/bindings/cyruntime.pyx.in
- cuda_bindings/docs/source/release/12.9.X-notes.rst
- cuda_bindings/docs/source/release/13.X.Y-notes.rst
- cuda_bindings/tests/test_cudart.py
> Fix #702: Update cyruntime.getLocalRuntimeVersion to use pathfinder

- cuda_bindings/cuda/bindings/_lib/utils.pxi.in
- cuda_bindings/cuda/bindings/driver.pyx.in
- cuda_bindings/cuda/bindings/nvrtc.pyx.in
- cuda_bindings/cuda/bindings/runtime.pyx.in
This should hopefully fix the one last remaining cycle, which is from `cuda.bindings.driver` to itself.
It hopefully will fix things similarly to @gflegar's solution (https://github.com/NVIDIA/cuda-python/issues/789#issuecomment-3293203821) without introducing any additional runtime checks.
> Fix #789: Remove self-cycle in cuda.bindings.driver

- cuda_core/cuda/core/experimental/_linker.py
The existing code checks for requested linker flags using "is not None" instead of testing for True/False. This can result in unwanted flags being passed to the linker in some instances. This change replaces the "is not None" check with simple boolean checks where appropriate.
> Replace is not None checks for linker flags with booleans

- cuda_bindings/cuda/bindings/cyruntime.pyx.in
Resulting from linting introduced in https://github.com/nvidia/cuda-python-private/pulls/150.
> style: clean up some whitespace from generated code

- ci/tools/run-tests
xref: https://github.com/NVIDIA/cuda-python/pull/953#discussion_r2355852675
> Fail if no "INFO test_" lines are found in pathfinder test output

- .github/workflows/build-wheel.yml
Fixes a misspelling that lead to a job step that never executed
> ci: fix misspelling that lead to code never being executed to verify free-threaded build

- ci/tools/run-tests
Small QoL enhancement to reduce the amount of noise coming out of the `run-tests` CI script
> ci: remove pwd and ls commands that add noise to CI output

- .github/actions/doc_preview/action.yml
- .github/workflows/release.yml
- .pre-commit-config.yaml
Add `actionlint` pre-commit-config step.
> chore(pre-commit): add actionlint pre-commit-config

- cuda_pathfinder/tests/conftest.py
See #1034 for background.
This compromise approach should prevent distracting unwanted output while retaining the concise summary that makes it easy to see at a glance that all found `abs_path`s line up.
> Produce `INFO summary` only if `pytest -v` option is present and `--iterations` is not present

- .pre-commit-config.yaml
Run autoupdate freeze on pre-commit and autofixed the lints produced by a newer version of ruff.
> chore(deps): bump precommit versions

- .github/workflows/ci.yml
> ci: replace single gating check with vanilla skipping (#1008) [no-ci]

- .pre-commit-config.yaml
This speeds up the markdown file disallowance when running pre-commit. This is noticeably slower when searching through hidden `.pixi` directories because it scans every single file in the directory. We only need to check that new markdown files are not introduced, so we only need to look at passed filenames.
> chore(dev-tools): only check specific files when checking for markdown in docs/source [no-ci]

- cuda_core/build_hooks.py
Found during local debugging with Andy.
> Fix skipping the check for nvidia-smi

- cuda_core/docs/source/getting-started.rst
- cuda_core/docs/source/release/0.X.Y-notes.rst
- cuda_core/examples/simple_multi_gpu_example.py
- cuda_core/examples/vector_add.py
The example kernel in the documentation uses `C[tid] = A[tid] + B[tid]` inside a loop, which should instead be `C[i] = A[i] + B[I]`, to correctly handle strided indexing across threads.
> [Docs]: Fix incorrect index usage in vector_add example in documentation

- cuda_bindings/cuda/bindings/_version.py
no need to change `docs/nv-versions.json` because we don't build docs for the backport branch (except for the release notes, which is done in the main branch).
> Bump `cuda.bindings` to 12.9.3
